version: "3"

services:
  app:
    restart: always
    # image: my-python
    build: .
    container_name: django-server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"